### ISSUE TITLE
Plugin crash when cluster takes longer than hour

### ISSUE THREAD

**Issue by andrew-s** [civo/terraform-provider-civo#139]
I'm not sure why, but cluster creation took over an hour and so the plugin timed out (the cluster still didn't build). However, when re-running the terraform to get the state from a 'building' state;

Prior run;

```
module.civo_kubernetes.civo_kubernetes_cluster.primary: Still creating... [59m41s elapsed]
module.civo_kubernetes.civo_kubernetes_cluster.primary: Still creating... [59m51s elapsed]
module.civo_kubernetes.civo_kubernetes_cluster.primary: Still creating... [1h0m1s elapsed]

Error: error waiting for cluster (**cluster-id**) to be created: timeout while waiting for state to become 'ACTIVE' (last state: 'BUILDING', timeout: 1h0m0s)
```

This then resulted in;

```
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

Stack trace from the terraform-provider-civo_v1.0.18 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 93 [running]:
github.com/civo/terraform-provider-civo/civo.flattenNodePool(0xc00000b680, 0xf3adab, 0xb, 0xddde00)
        /home/runner/work/terraform-provider-civo/terraform-provider-civo/civo/resource_kubernetes_cluster.go:484 +0x579
github.com/civo/terraform-provider-civo/civo.resourceKubernetesClusterRead(0x10d4e78, 0xc000189440, 0xc0005ee780, 0xf31620, 0xc000382640, 0xc0006d4340, 0xc00061b908, 0x40e0f8)
        /home/runner/work/terraform-provider-civo/terraform-provider-civo/civo/resource_kubernetes_cluster.go:359 +0x973
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0000feee0, 0x10d4e08, 0xc0003c4480, 0xc0005ee780, 0xf31620, 0xc000382640, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000feee0, 0x10d4e08, 0xc0003c4480, 0xc000384070, 0xf31620, 0xc000382640, 0xc0005dcd00, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012e228, 0x10d4e08, 0xc0003c4480, 0xc0003c44c0, 0xc0003c4480, 0x40b965, 0xeb65e0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0001391c0, 0x10d4eb0, 0xc0003c4480, 0xc000188d80, 0xc0001391c0, 0xc00040b7d0, 0xc000675ba0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0xeef480, 0xc0001391c0, 0x10d4eb0, 0xc00040b7d0, 0xc000667f80, 0x0, 0x10d4eb0, 0xc00040b7d0, 0xc0006c8000, 0x264)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00043ddc0, 0x10ddd58, 0xc00018bc80, 0xc0005e4600, 0xc0002be120, 0x15e1990, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00043ddc0, 0x10ddd58, 0xc00018bc80, 0xc0005e4600, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00003c250, 0xc00043ddc0, 0x10ddd58, 0xc00018bc80, 0xc0005e4600)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-civo_v1.0.18 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I'm not sure how common this is but it seems that it isn't handled in the TF.

**Comment by alessandroargentieri** [comment]
@andrew-s did you have the chance to try the command again? Was this error systematic or happened (for some reasons) just once? Thanks for reporting!

**Comment by andrew-s** [comment]
@alessandroargentieri This was because the cluster name was too long, and some internal components failed - I retried with a shorter name at the time and it then worked, so I'm unsure if;

1) The TF plugin handles responses from the API better
2) Longer names are now supported

Hope that helps!

**Comment by alejandrojnm** [comment]
HI @andrew-s @jarededwards it possible to see the TF for this ?? also in what region is this ??

**Comment by jarededwards** [comment]
hi @alejandrojnm , this is in the `NYC1` region here is the [terraform code](https://gist.github.com/jarededwards/7e20522e40896297e7ca7d0e794b05b8)  i executed, i tried to keep it as minimal as possible

**Comment by jarededwards** [comment]
also if its helpful, this morning i just updated to latest (`1.3.5`) but have not re-executed
```terraform version                                                           
Terraform v1.2.6
on darwin_arm64```

**Comment by alejandrojnm** [comment]
Hi @jarededwards and @andrew-s we found a bug in the NYC1 region but it is already done and fixed, Please can you try again and let me know to close this issue.

**Comment by jarededwards** [comment]
hey @alejandrojnm thanks so much for the quick turn around. I was able to provision a new cluster in `NYC1` this morning! thanks for looking into this so quickly. I will continue testing next week when i am back at work! looking forward to using civo more!
```
Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

civo_network.kubefirst: Creating...
civo_network.kubefirst: Creation complete after 3s [id=9f535a69-c330-495b-aadb-1dd2dfde4418]
civo_firewall.kubefirst: Creating...
civo_firewall.kubefirst: Creation complete after 1s [id=0fa68bd2-dd59-4cb6-8155-2bd0e0e989d5]
civo_kubernetes_cluster.kubefirst: Creating...
civo_kubernetes_cluster.kubefirst: Still creating... [10s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [20s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [30s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [40s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [50s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m0s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m10s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m20s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m30s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m40s elapsed]
civo_kubernetes_cluster.kubefirst: Still creating... [1m50s elapsed]
civo_kubernetes_cluster.kubefirst: Creation complete after 1m58s [id=]
```
