### ISSUE TITLE
Importing a node pool crashes

### ISSUE THREAD

**Issue by bcdrme** [civo/terraform-provider-civo#47]
`terraform import civo_kubernetes_node_pool.main <node-id>:<pool:id>` results in 

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-civo_v0.10.9 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd41cd1]

goroutine 25 [running]:
github.com/civo/terraform-provider-civo/civo.resourceKubernetesClusterNodePoolImport(0xc0005bfb80, 0xf27520, 0xc0001abf40, 0x19, 0xc000127490, 0x1, 0x30, 0x7f49572da5b8)
        /home/runner/work/terraform-provider-civo/terraform-provider-civo/civo/resource_kubernetes_cluster_nodepool.go:229 +0x191
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc00052a280, 0x10ca6c8, 0xc000662e80, 0xc000653aa8, 0xc000216500, 0x49, 0x203000, 0x203000, 0x203000, 0x0, ...)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/provider.go:369 +0x328
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc00012e498, 0x10ca6c8, 0xc000662e80, 0xc000674640, 0xc000662e80, 0xee6060, 0xc000655800)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:1021 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ImportResourceState(0xc00065e160, 0x10ca770, 0xc000662e80, 0xc00008d5e0, 0xc00065e160, 0xc000655860, 0xc000302ba0)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:349 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler(0xee6060, 0xc00065e160, 0x10ca770, 0xc000655860, 0xc000083500, 0x0, 0x10ca770, 0xc000655860, 0xc0003141c0, 0x66)
        /home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d6000, 0x10d3298, 0xc000001680, 0xc000468200, 0xc0004026c0, 0x15d60d8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000d6000, 0x10d3298, 0xc000001680, 0xc000468200, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0006561c0, 0xc0000d6000, 0x10d3298, 0xc000001680, 0xc000468200)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-civo_v0.10.9 plugin crashed!
```

**Comment by zulh-civo** [comment]
I will look at this

**Comment by zulh-civo** [comment]
@bcdrme can you share the steps to reproduce this? I just give it a try and it's working on my end.

![Screenshot 2021-08-05 at 3 43 11 PM](https://user-images.githubusercontent.com/75463191/128311605-c1142fac-0779-44b2-b6da-fa1552b4cd07.png)

I think you were using incorrect command (`terraform import civo_kubernetes_node_pool.main <node-id>:<pool:id>`). The [documentation](https://github.com/civo/terraform-provider-civo/blob/master/docs/resources/kubernetes_node_pool.md#import) says:

> Then the Kubernetes cluster node pool can be imported using the cluster's and pool id `cluster_id:node_pool_id`

Can you try `terraform import civo_kubernetes_node_pool.main cluster_id:node_pool_id`?

**Comment by bcdrme** [comment]
It's a typo in my original post. I'm indeed running `terraform import civo_kubernetes_node_pool.main cluster_id:node_pool_id` and the plugin crashes.

1. add a new node pool to an existing cluster using CIVO.com admin dashboard
2. edit the terraform configuration, here's the relevant part:
```
resource "civo_kubernetes_cluster" "civo_cluster" {
  name              = var.cluster_name
  applications      = ""
  num_target_nodes  = 4
  target_nodes_size = "g3.k3s.medium"
  region            = var.cluster_region
}

data "civo_kubernetes_cluster" "civo_cluster" {
  name = civo_kubernetes_cluster.civo_cluster.name
}

resource "civo_kubernetes_node_pool" "gitlab" {
  cluster_id        = civo_kubernetes_cluster.civo_cluster.id
  num_target_nodes  = 1
  target_nodes_size = "g3.k3s.medium"
  region            = var.cluster_region
}
```
3. run `terraform import civo_kubernetes_node_pool.main cluster_id:node_pool_id`  -> crash

**Comment by zulh-civo** [comment]
@bcdrme - I try again today by doing a few tests but I'm not able to reproduce this still. Maybe I missed something. Could you run `export TF_LOG=INFO` in your shell, run it again and share the terminal outputs here? Or, if you want to screenrecord all the steps and attach it here, that would be very helpful for me to see where the issue is. Thank you.

**Comment by zulh-civo** [comment]
I'm closing this due to inactivity. Feel free to reopen if the problem persist. Thanks.
